compRecMS: driver.c merge.c recMergeSort.c readElement.c element.h readElement.h
	gcc -o runREC driver.c merge.c recMergeSort.c readElement.c element.h readElement.h

compIterMS: driver.c merge.c iterMergeSort.c readElement.c element.h readElement.h
	gcc -o runIter driver.c merge.c iterMergeSort.c readElement.c element.h readElement.h
		
runRecMS:compRecMS
	./runREC

runIterMS:compIterMS
	./runIter
	
	
